### ISSUE TITLE
Promise doesn't resolve when user cancel selecting files

### ISSUE THREAD

**Issue by raqso** [danisss9/easy-file-picker#1]
It should be handled somehow because right now we're not able to catch this in our code. It could be done via:
- returning empty files array
- returning object with a filed `cancelled: true`, similar to https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickercanceledresult
- rejecting the Promise

The second option would be propably the best, but would also require changing API/types a little bit.

#### Reproduction
https://codesandbox.io/p/sandbox/easy-file-picker-cancel-x6mhrl?file=%2Fsrc%2FApp.tsx

### Possible second solution
![Zrzut ekranu 2024-02-14 o 07 18 28](https://github.com/danisss9/easy-file-picker/assets/13930984/11cd9c00-0c06-454b-8b09-c3bfedff75a0)

**Comment by danisss9** [comment]
Will make GetFile() return null and GetFiles() return empty array.

**Comment by danisss9** [comment]
Resolved in version 1.1.0
